spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-service
  rabbitmq:
    host: polar-rabbitmq
  redis:
    host: polar-redis
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://host.docker.internal:8080/auth/realms/PolarBookshop