apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/PolarBookshop/edge-service/edge-service/k8s?ref=v0.0.1

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml
- path: patch-ingress.yml
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: polar-ingress

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-service

images:
- name: edge-service
  newName: ghcr.io/polarbookshop/edge-service
  newTag: 0.0.1

replicas:
- count: 1
  name: edge-service
