version: "3.8"
services:

  # Applications

  catalog-service:
    depends_on:
      - polar-postgres-catalog
    image: "polarbookshop/catalog-service:0.0.1-SNAPSHOT"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # JVM environment variable to enable debug through a socket on port 8001
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres-catalog:5432/polardb_catalog
  
  config-service:
    image: "polarbookshop/config-service:0.0.1-SNAPSHOT"
    container_name: "config-service"
    ports:
      - 8888:8888
      - 9888:9888
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # JVM environment variable to enable debug through a socket on port 9888
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9888

  # Backing Services

  polar-postgres-catalog:
    image: "postgres:13.4"
    container_name: "polar-postgres-catalog"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polardb_catalog
