apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/PolarBookshop/order-service/k8s?ref=v0.0.1

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-service

images:
- name: order-service
  newName: ghcr.io/polarbookshop/order-service
  newTag: 0.0.1

replicas:
- count: 1
  name: order-service
