apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  template:
    spec:
      containers:
        - name: catalog-service
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "100"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            # - name: JAVA_TOOL_OPTIONS
            #   value: -javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-1.33.3.jar
            # - name: OTEL_SERVICE_NAME
            #   value: catalog-service
            # - name: OTEL_METRICS_EXPORTER
            #   value: none
            # - name: OTEL_EXPORTER_OTLP_ENDPOINT
            #   value: http://tempo.observability-stack.svc.cluster.local:4317
