version: "3.8"
services:

  # Applications

  catalog-service:
    depends_on:
      - fluent-bit
      - polar-keycloak
      - polar-postgres
      - tempo
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # Buildpacks environment variable to enable debug through a socket on port 8001
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://host.docker.internal:8080/auth/realms/PolarBookshop
      - SPRING_ZIPKIN_ENABLED=true
      - ZIPKIN_URL=http://tempo:9411
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  order-service:
    depends_on:
      - fluent-bit
      - polar-keycloak
      - polar-postgres
      - tempo
    image: "order-service"
    container_name: "order-service"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8002
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - POLAR_CATALOG_SERVICE_URI=http://catalog-service:9001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_RABBITMQ_HOST=polar-rabbitmq
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://host.docker.internal:8080/auth/realms/PolarBookshop
      - SPRING_ZIPKIN_ENABLED=true
      - ZIPKIN_URL=http://tempo:9411
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  dispatcher-service:
    depends_on:
      - fluent-bit
      - polar-rabbitmq
      - tempo
    image: "dispatcher-service"
    container_name: dispatcher-service
    ports:
      - 9003:9003
      - 8003:8003
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8002
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8003
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_RABBITMQ_HOST=polar-rabbitmq
      - SPRING_ZIPKIN_ENABLED=true
      - ZIPKIN_URL=http://tempo:9411
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  edge-service:
    depends_on:
      - fluent-bit
      - polar-keycloak
      - polar-redis
      - tempo
    image: "edge-service"
    container_name: "edge-service"
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8000
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002
      - SPA_URL=http://polar-ui:9004
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_REDIS_HOST=polar-redis
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://host.docker.internal:8080/auth/realms/PolarBookshop
      - SPRING_ZIPKIN_ENABLED=true
      - ZIPKIN_URL=http://tempo:9411
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  config-service:
    depends_on:
      - fluent-bit
      - tempo
    image: "config-service"
    container_name: "config-service"
    ports:
      - 8888:8888
      - 9888:9888
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # Buildpacks environment variable to enable debug through a socket on port 9888
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888
      - SPRING_ZIPKIN_ENABLED=true
      - ZIPKIN_URL=http://tempo:9411
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  polar-ui:
    image: "ghcr.io/polarbookshop/polar-ui:latest"
    container_name: "polar-ui"
    ports:
      - 9004:9004

  # Backing Services
  
  polar-postgres:
    image: "postgres:14.1"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  polar-redis:
    image: "redis:6.2"
    container_name: "polar-redis"
    ports:
      - 6379:6379

  polar-rabbitmq:
    image: rabbitmq:3.9-management
    container_name: polar-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  
  polar-keycloak:
    image: quay.io/keycloak/keycloak:17.0.0-legacy
    container_name: "polar-keycloak"
    volumes:
      - ./keycloak:/opt/jboss/keycloak/imports
    environment:
      - KEYCLOAK_USER=user
      - KEYCLOAK_PASSWORD=password
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/full-realm-export.json
    ports:
      - 8080:8080

  # Observability

  grafana:
    image: grafana/grafana:8.4.4
    container_name: grafana
    depends_on:
      - loki
      - prometheus
      - tempo
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./platform/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./platform/grafana/dashboards:/etc/grafana/provisioning/dashboards
  
  loki:
    image: grafana/loki:2.4.2
    container_name: loki
    depends_on:
      - fluent-bit
    ports:
      - "3100:3100"
  
  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./platform/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
  
  tempo:
    image: grafana/tempo:1.3.2
    container_name: tempo
    command: -config.file /etc/tempo-config.yml
    volumes:
      - ./platform/tempo/tempo.yml:/etc/tempo-config.yml
    ports:
      - "3101:3100"     # Tempo
      - "9411:9411"     # Zipkin

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:2.4.2-amd64
    container_name: fluent-bit
    ports:
      - "24224:24224"
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./platform/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
  