version: "3.8"
services:
  polar-postgres-catalog:
    image: "postgres:13"
    container_name: "polar-postgres-catalog"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=polardb_catalog

  catalog-service:
    depends_on:
      - config-service
      - polar-keycloak
      - polar-postgres-catalog
      - polar-rabbitmq
    image: "polarbookshop/catalog-service:0.0.1-SNAPSHOT"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # JVM environment variable to enable debug through a socket on port 8001
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8001
      - KEYCLOAK_URL=http://host.docker.internal:8080
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres-catalog:5432/polardb_catalog
      - SPRING_RABBITMQ_HOST=polar-rabbitmq

  config-service:
    depends_on:
      - polar-rabbitmq
    image: "polarbookshop/config-service:0.0.1-SNAPSHOT"
    container_name: "config-service"
    ports:
      - 8888:8888
      - 9888:9888
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # JVM environment variable to enable debug through a socket on port 9888
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9888

  polar-postgres-order:
    image: "postgres:13"
    container_name: "polar-postgres-order"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=polardb_order

  order-service:
    depends_on:
      - config-service
      - polar-keycloak
      - polar-rabbitmq
      - polar-postgres-order
    image: "polarbookshop/order-service:0.0.1-SNAPSHOT"
    container_name: "order-service"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      # JVM environment variable to enable debug through a socket on port 8002
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8002
      - KEYCLOAK_URL=http://host.docker.internal:8080
      - POLAR_CATALOG_SERVICE_URL=http://catalog-service:9001/books/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://polar-postgres-order:5432/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://polar-postgres-order:5432/polardb_order
      - SPRING_RABBITMQ_HOST=polar-rabbitmq
  
  polar-redis:
    image: "redis:6"
    container_name: "polar-redis"
    ports:
      - 6379:6379

  edge-service:
    depends_on:
      - config-service
      - polar-keycloak
      - polar-rabbitmq
      - polar-redis
    image: "polarbookshop/edge-service:0.0.1-SNAPSHOT"
    container_name: "edge-service"
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      # JVM environment variable to enable debug through a socket on port 8000
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - KEYCLOAK_URL=http://host.docker.internal:8080
      - ORDER_SERVICE_URL=http://order-service:9002
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_RABBITMQ_HOST=polar-rabbitmq
      - SPRING_REDIS_HOST=polar-redis
  
  polar-rabbitmq:
    image: rabbitmq:3-management
    container_name: polar-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  dispatcher-service:
    depends_on:
      - config-service
      - polar-rabbitmq
    image: polarbookshop/dispatcher-service:0.0.1-SNAPSHOT
    container_name: dispatcher-service
    ports:
      - 8003:8003
    environment:
      # JVM environment variable to enable debug through a socket on port 8003
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8003
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_RABBITMQ_HOST=polar-rabbitmq

  polar-keycloak:
    image: jboss/keycloak:14.0.0
    container_name: "polar-keycloak"
    volumes:
      - ./keycloak:/opt/jboss/keycloak/imports
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/full-realm-export.json"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080
