spring:
  config:
    import: optional:configserver:,configtree:/workspace/secrets/*/
  cloud:
    config:
      uri: http://config-service
  rabbitmq:
    host: polar-rabbitmq
  redis:
    host: polar-redis-master