name: CD Pipeline
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Compile and test application
        run: |
          chmod +x gradlew
          ./gradlew build
  package:
    name: Package
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Get project version
        uses: thecodemonkey/action-get-gradle-version@master
        id: version
      - name: Save app version as environment variable
        run: |
          echo "APP_VERSION=${{ steps.version.outputs.version }}" >> $GITHUB_ENV
      - name: Containerize and publish image
        run: |
          chmod +x gradlew
          ./gradlew bootBuildImage \
            --imageName ghcr.io/polarbookshop/edge-service:${{ env.APP_VERSION }} \
            --publishImage \
            -PregistryUrl=ghcr.io \
            -PregistryUsername=polarbookshop \
            -PregistryToken=${{ secrets.GITHUB_TOKEN }}
      - name: Trigger application release in the deployment repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN_REPO }}
          repository: ${{ github.event.repository.owner.name }}/polar-deployment
          event-type: release_app_event
          client-payload: '{
                "app_image": "ghcr.io/polarbookshop/edge-service",
                "app_name": "edge-service",
                "app_tag": "${{ github.ref_name }}",
                "app_version": "${{ env.APP_VERSION }}"
              }'
