apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: config-service
  namespace: flux-system
spec:
  interval: 30s
  path: ./kubernetes/applications/config-service/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: applications
  targetNamespace: default
